"""career guide

Revision ID: 3eb12f42ef90
Revises: 6f24052f98ca
Create Date: 2025-12-10 16:26:16.684959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb12f42ef90'
down_revision: Union[str, Sequence[str], None] = '6f24052f98ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_test_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_test_sessions_id'), 'career_test_sessions', ['id'], unique=False)
    op.create_table('career_test_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['career_test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_test_answers_id'), 'career_test_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_test_answers_id'), table_name='career_test_answers')
    op.drop_table('career_test_answers')
    op.drop_index(op.f('ix_career_test_sessions_id'), table_name='career_test_sessions')
    op.drop_table('career_test_sessions')
    # ### end Alembic commands ###
