"""sync tables

Revision ID: 3ff488dbadbb
Revises: skill_tree_001
Create Date: 2025-12-23 21:11:12.283565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff488dbadbb'
down_revision: Union[str, Sequence[str], None] = 'skill_tree_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_challenge_submissions_user_id', table_name='challenge_submissions')
    op.drop_index('ix_employer_challenges_skill_id', table_name='employer_challenges')
    op.drop_index('ix_skill_materials_rating', table_name='skill_materials')
    op.drop_index('ix_skill_materials_skill_id', table_name='skill_materials')
    op.drop_index('ix_skills_is_global', table_name='skills')
    op.drop_index('ix_user_skill_progress_skill_id', table_name='user_skill_progress')
    op.drop_index('ix_user_skill_progress_user_id', table_name='user_skill_progress')
    op.add_column('users', sa.Column('achievements_json', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('notifications_json', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferences_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences_json')
    op.drop_column('users', 'notifications_json')
    op.drop_column('users', 'achievements_json')
    op.create_index('ix_user_skill_progress_user_id', 'user_skill_progress', ['user_id'], unique=False)
    op.create_index('ix_user_skill_progress_skill_id', 'user_skill_progress', ['skill_id'], unique=False)
    op.create_index('ix_skills_is_global', 'skills', ['is_global'], unique=False)
    op.create_index('ix_skill_materials_skill_id', 'skill_materials', ['skill_id'], unique=False)
    op.create_index('ix_skill_materials_rating', 'skill_materials', ['rating'], unique=False)
    op.create_index('ix_employer_challenges_skill_id', 'employer_challenges', ['skill_id'], unique=False)
    op.create_index('ix_challenge_submissions_user_id', 'challenge_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###
