"""add skill tree tables

Revision ID: a593c51669c6
Revises: skill_tree_001
Create Date: 2025-12-23 18:54:39.023192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a593c51669c6'
down_revision: Union[str, Sequence[str], None] = 'skill_tree_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employer_challenges_id', table_name='employer_challenges')
    op.drop_index('ix_employer_challenges_skill_id', table_name='employer_challenges')
    op.drop_table('employer_challenges')
    op.drop_index('ix_challenge_submissions_id', table_name='challenge_submissions')
    op.drop_index('ix_challenge_submissions_user_id', table_name='challenge_submissions')
    op.drop_table('challenge_submissions')
    op.drop_index('ix_material_ratings_id', table_name='material_ratings')
    op.drop_table('material_ratings')
    op.drop_index('ix_skills_id', table_name='skills')
    op.drop_index('ix_skills_is_global', table_name='skills')
    op.drop_index('ix_skills_name', table_name='skills')
    op.drop_table('skills')
    op.drop_index('ix_user_skill_progress_id', table_name='user_skill_progress')
    op.drop_index('ix_user_skill_progress_skill_id', table_name='user_skill_progress')
    op.drop_index('ix_user_skill_progress_user_id', table_name='user_skill_progress')
    op.drop_table('user_skill_progress')
    op.drop_index('ix_skill_materials_id', table_name='skill_materials')
    op.drop_index('ix_skill_materials_rating', table_name='skill_materials')
    op.drop_index('ix_skill_materials_skill_id', table_name='skill_materials')
    op.drop_table('skill_materials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_materials',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('skill_materials_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('lecture', 'video', 'code_task', '3d_model', 'article', 'quiz', name='materialtype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('approved', 'pending_review', 'rejected', name='materialstatus'), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='skill_materials_author_id_fkey'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='skill_materials_reviewed_by_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='skill_materials_skill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='skill_materials_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_skill_materials_skill_id', 'skill_materials', ['skill_id'], unique=False)
    op.create_index('ix_skill_materials_rating', 'skill_materials', ['rating'], unique=False)
    op.create_index('ix_skill_materials_id', 'skill_materials', ['id'], unique=False)
    op.create_table('user_skill_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('locked', 'in_progress', 'verified', name='skillstatus'), autoincrement=False, nullable=True),
    sa.Column('progress_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('materials_completed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('proof_artifact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('proof_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verification_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verified_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='user_skill_progress_skill_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_skill_progress_user_id_fkey'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='user_skill_progress_verified_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_skill_progress_pkey')
    )
    op.create_index('ix_user_skill_progress_user_id', 'user_skill_progress', ['user_id'], unique=False)
    op.create_index('ix_user_skill_progress_skill_id', 'user_skill_progress', ['skill_id'], unique=False)
    op.create_index('ix_user_skill_progress_id', 'user_skill_progress', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('skills_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_global', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('specialty_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('syllabus_source_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prerequisites_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['skills.id'], name='skills_parent_id_fkey'),
    sa.ForeignKeyConstraint(['specialty_id'], ['professions.id'], name='skills_specialty_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='skills_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_skills_name', 'skills', ['name'], unique=False)
    op.create_index('ix_skills_is_global', 'skills', ['is_global'], unique=False)
    op.create_index('ix_skills_id', 'skills', ['id'], unique=False)
    op.create_table('material_ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['skill_materials.id'], name='material_ratings_material_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='material_ratings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='material_ratings_pkey')
    )
    op.create_index('ix_material_ratings_id', 'material_ratings', ['id'], unique=False)
    op.create_table('challenge_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submission_file', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('submission_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_check_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('manual_check_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checked_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['employer_challenges.id'], name='challenge_submissions_challenge_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='challenge_submissions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='challenge_submissions_pkey')
    )
    op.create_index('ix_challenge_submissions_user_id', 'challenge_submissions', ['user_id'], unique=False)
    op.create_index('ix_challenge_submissions_id', 'challenge_submissions', ['id'], unique=False)
    op.create_table('employer_challenges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('verification_type', postgresql.ENUM('ai_vision', 'manual_employer', 'auto_test', name='verificationtype'), autoincrement=False, nullable=False),
    sa.Column('ai_validation_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certificate_template', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deadline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], name='employer_challenges_employer_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='employer_challenges_skill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employer_challenges_pkey')
    )
    op.create_index('ix_employer_challenges_skill_id', 'employer_challenges', ['skill_id'], unique=False)
    op.create_index('ix_employer_challenges_id', 'employer_challenges', ['id'], unique=False)
    # ### end Alembic commands ###
