"""added new tables

Revision ID: da6a99a252ad
Revises: 34f14c8435b4
Create Date: 2025-12-05 19:52:07.535789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6a99a252ad'
down_revision: Union[str, Sequence[str], None] = '34f14c8435b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professions_code'), 'professions', ['code'], unique=True)
    op.create_index(op.f('ix_professions_id'), 'professions', ['id'], unique=False)
    op.create_index(op.f('ix_professions_name'), 'professions', ['name'], unique=False)
    op.create_table('university_professions',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('university_id', 'profession_id')
    )
    op.add_column('universities', sa.Column('history_json', sa.JSON(), nullable=True))
    op.add_column('universities', sa.Column('contacts_json', sa.JSON(), nullable=True))
    op.add_column('universities', sa.Column('achievements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'achievements')
    op.drop_column('universities', 'contacts_json')
    op.drop_column('universities', 'history_json')
    op.drop_table('university_professions')
    op.drop_index(op.f('ix_professions_name'), table_name='professions')
    op.drop_index(op.f('ix_professions_id'), table_name='professions')
    op.drop_index(op.f('ix_professions_code'), table_name='professions')
    op.drop_table('professions')
    # ### end Alembic commands ###
